builders:
  preferencesBuilder:
    import: "package:bmflutter/build.dart"
    builder_factories: ["preferencesBuilder"]
    build_extensions: {".dart": [".pref.g.dart"]}
    auto_apply: root_package
    build_to: source