builders:
  preferencesBuilder:
    import: "package:ld_flutter/build.dart"
    builder_factories: ["preferencesBuilder"]
    build_extensions: {".dart": [".pref.g.dart"]}
    auto_apply: dependents
    build_to: source