name: bmflutter
description: "A new Flutter project."
version: 0.0.1
homepage: ""

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking & Connectivity
  http: ^1.6.0
  http_parser: ^4.1.2
  connectivity_plus: ^7.0.0

  # State Management
  flutter_bloc: ^9.1.1

  # Storage & Persistence
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0

  # Security & Cryptography
  pointycastle: ^4.0.0
  crypto: ^3.0.6

  # Platform Utilities
  jailbreak_root_detection: ^1.2.0+1
  root_jailbreak_sniffer: ^1.1.4

  # UI & Framework
  provider: ^6.1.1
  meta: ^1.17.0
  source_gen: ^4.2.0
  build: ^4.0.4
  analyzer: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1